on:
  schedule:
  - cron: 0 0 * * *

jobs:
  get-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Update branch
        run: git checkout main
  # call-esg-ci:
  #   runs-on: esgci
  #   steps:
  #     - name: Ignored by ESG CI runner
  #       shell: Ignored by ESG CI runner
  #       run: Ignored by ESG CI runner
