# a comment
on:
  pull_request:
    types: [ opened, reopened, edited ]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    if: contains(${{ github.ref_name }}, 'WINEP-')
    steps:
    - name: Extract JIRA ticket
      id: extract
      run: echo ::set-output name=jira_ticket::"$(echo ${{ github.head_ref || github.ref_name }} | grep -oP 'WINEP-[0-9]*')"
    - name: Add label
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: "Hi 👋, the JIRA ticket [${{ steps.extract.output.jira_ticket }}](https://www.jira.sophos.net/browse/${{ steps.extract.output.jira_ticket }}) was extracted from the branch name."
          })
    # - name: Get pull request title
    #   shell: bash
    #   run: echo "::set-output name=new_pull_request_title $(echo ${github.event.pull_request.title#'[DO NOT MERGE] '})"
    #   id: extract
    # - name: Remove [DO NOT MERGE] from pull request title
    #   uses: actions/github-script@v6
    #   with:
    #     script: |
    #       github.rest.pulls.update({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         pull_number: context.issue.number,
    #         title: "${{ steps.extract.output.new_pull_request_title }}"
    #       })
    # - name: Add DO NOT MERGE label to pull request issue
    #   uses: actions/github-script@v6
    #   with:
    #     script: |
    #       github.rest.issues.addLabels({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         issue_number: context.issue.number,
    #         labels: ['DO NOT MERGE']
    #       })
